// projects.jsx — case studies structured as a story plus a UX record:
// Problem → Discover → Design → Solution → Testing, with the pivot called out.
// **bold** renders as <strong>. Exports window.PROJECTS + window.Rich.
(() => {
  const P = [
    {
      id: 'designquest', personal: true, client: 'Design Quest', tint: 'var(--violet)', year: '2026',
      title: 'A portfolio built as a playable RPG — shipped in days',
      role: 'Lead Product Designer · AI-assisted development', dates: '2026', discipline: 'Game / portfolio',
      cats: ['ai', 'zero-to-one'], demo: 'designquest',
      headline: { v: 'Days', l: 'concept to shipped, live product' },
      story: 'Design Quest is a browser-based top-down RPG where the player walks through a town, enters buildings, and discovers case studies, skills, and résumé history. The game is the portfolio. It is live, playable in the browser, and it went from idea to shipped in days.',
      pivot: { h: 'The pivot', b: 'The question was never “how do I show my case studies.” It was **“how do I create an experience someone will actually remember and talk about.”** Once the brief changed, a grid of cards stopped being an option.' },
      sections: [
        { k: 'Problem', b: ['Standard design portfolios follow the same pattern: a grid of case-study cards, click in, read, click out. The interaction cost is high, differentiation is low, and the format signals polish rather than thinking.', 'Portfolios are passive. Visitors scan, then leave.'] },
        { k: 'Discover', b: ['I chose the RPG format for UX reasons rather than novelty. **Universal controls** — arrow keys, walk, enter — need no tutorial, because top-down RPGs have an immediately legible interaction model.', 'Exploration also converts browsing into agency: the visitor decides what to open, which is the same reason the concierge exists.'] },
        { k: 'Design', b: ['Every mechanic had a design reason. Buildings map to sections, so spatial memory does the work a nav would do. Entering a building is a deliberate act, which raises intent before content appears.'] },
        { k: 'Solution', b: ['A town you walk. Case studies, skills, and history live in places rather than on a page — so the visit is a route the visitor chose, not a scroll they endured.'] },
        { k: 'Testing', b: ['This is where AI-assisted development mattered: the build cycle was short enough to test the format itself rather than argue about it. Shipping in days meant the concept could be validated live instead of in a deck.'] },
      ],
      result: ['A **live, shipped, playable** product, not a concept', 'Demonstrates product design, game feel, and AI-assisted delivery at once', 'Doubles as the portfolio it is describing'],
      metrics: [{ v: 'Days', l: 'idea to live' }, { v: '0', l: 'tutorial needed' }, { v: '1', l: 'product doing two jobs' }],
      shots: ['The town — buildings as sections', 'Entering a case study building'],
      note: 'Playable from the Live products answer. Swap in real gameplay stills or a screen recording for the two slots.',
    },
    {
      id: 'screener', personal: true, client: 'VC Stock Screener', tint: 'var(--violet)', year: '2026',
      title: 'A screener that answers “is this worth my afternoon?” first',
      role: 'Designer + builder (solo)', dates: '2026', discipline: 'Fintech tool',
      cats: ['numbers', 'zero-to-one'], demo: 'screener',
      headline: { v: 'Live', l: 'shipped and running in the browser' },
      story: 'Most screeners open with a wall of columns and make you become an analyst before they tell you anything. This one opens with a judgment: is this name worth more of your time, yes or no — and only then shows you the evidence behind that call.',
      pivot: { h: 'The pivot', b: 'The instinct with a screener is to add filters. **The useful move was to lead with a verdict and put the data underneath it** — so the first screen answers a question instead of asking twenty.' },
      sections: [
        { k: 'Problem', b: ['Screening tools optimise for completeness, which pushes the interpretation work onto the user at exactly the moment they have the least context.'] },
        { k: 'Discover', b: ['The real task is triage, not analysis: most names get eliminated in seconds, and the tool should be fastest at the thing that happens most.'] },
        { k: 'Design', b: ['Verdict first, evidence second. Density is earned — the detail appears once you have said you care about this name.'] },
        { k: 'Solution', b: ['A screener you can run through quickly on a phone, live in the browser right now.'] },
        { k: 'Testing', b: ['Shipped and in use; it is embedded in this page so you can try it rather than take my word for it.'] },
      ],
      result: ['Designed and built solo, **live in production**', 'Triage-first interaction model instead of filter-first'],
      metrics: [{ v: 'Live', l: 'in production' }, { v: 'Solo', l: 'design + build' }, { v: 'Phone', l: 'primary form factor' }],
      shots: ['Verdict view', 'Evidence underneath'],
      note: 'Thin on specifics — send me the real story (why you built it, what you learned, any usage numbers) and I will write this one properly.',
    },
    {
      id: 'doctronic', client: 'Doctronic', tint: 'var(--violet)', year: '2026',
      title: 'The first AI-authorized prescription refill in the US',
      role: 'Product Design Lead, AI Health', dates: 'Feb 2026 – Jun 2026', discipline: 'AI health',
      cats: ['ai', 'health', 'zero-to-one'],
      headline: { v: '0.04% → 6%', l: 'eligibility-to-decision conversion target' },
      story: 'Doctronic shipped the first AI-authorized prescription refill in the United States — Utah patients refilling eligible medications online with no in-person visit, covered by the Washington Post, Politico and the Salt Lake Tribune. The clinical milestone landed. The funnel did not: **96% of Utah users dropped off without completing a refill, and left no contact information behind.** Every one of them was a permanent loss. I joined as Lead Product Designer to own the redesign end to end, from funnel diagnosis through shipping.',
      pivot: { h: 'The pivot', b: 'The hardest problem was never the UI — it was **trust architecture**. Geolocation firing on step two, identity verification, prescription data appearing without warning: these were not friction points, they were trust violations. You cannot optimise a funnel whose trust is broken at step two.' },
      sections: [
        { k: 'Problem', b: ['A first-in-the-US clinical product with a critically broken funnel. No lifecycle infrastructure, no re-engagement touchpoints, and no early conversion event for paid campaigns to optimise against — so every drop-off was unrecoverable and unmeasurable at once.'] },
        { k: 'Discover', b: ['Before redesigning anything I mapped the full funnel across a one-week window with the PM and engineering lead. The data named the leak precisely.'],
          blocks: [
            { type: 'funnel', head: ['Funnel step', 'Users', '% traffic'], rows: [
              ['Qualified Utah traffic', '56,173', '—'], ['Start refill click', '2,271', '4.04%'],
              ['Utah check pass', '1,613', '2.9%'], ['Medication name submit', '1,117', '1.96%'],
              ['IDV verified click', '1,013', '1.8%'], ['IDV verified success — 72% drop', '288', '0.5%', 'warn'],
              ['Completed conversation', '40', '0.07%'], ['Checkout success', '22', '0.04%'],
            ] },
            { type: 'callout', h: 'Key insight', b: 'Up to **60% of top-of-funnel users were not actually in Utah** — self-attesting incorrectly, which inflated the apparent drop-off. The real problem was identity verification causing **72% abandonment**, with no re-engagement path for anyone who left.' },
          ] },
        { k: 'My role', b: ['I worked directly with the PM and the engineering/compliance lead across three workstreams simultaneously, not sequentially.'],
          list: ['**Original launch** — the 11-step refill flow, medication eligibility through checkout and confirmation',
            '**Conversion roadmap** — the phased v0–v3 strategy, prioritised by impact against engineering effort',
            '**Lifecycle infrastructure** — DPG async refill flow, 3-state prescription status, deep-link session state',
            '**Copy & positioning** — the shift from “refills” to “renewals,” trust signals, FAQ and press-bar language'] },
        { k: 'Design', b: ['Three versions of the same flow over six months.'],
          blocks: [{ type: 'timeline', items: [
            { d: 'February 2026', t: '10-step form-based experience', b: 'Entry → med search → GPS location check → OTP/IDV → email → Rx match → AI chat → dosing → pharmacy → payment. The GPS prompt fired on step 2, before the user had built any trust. IDV caused 72% drop-off. No re-engagement infrastructure.' },
            { d: 'Spring 2026', t: 'Conversion redesign explorations', b: 'Tested removing geolocation in favour of pharmacy-screen self-attestation; shifting the primary CTA from “start your refill” to phone capture; explicit Surescripts opt-in; “renewals” positioning. Multiple landing-page variants A/B tested.' },
            { d: 'June 2026 — shipped', t: 'Chat-based redesign', b: 'Landing (phone capture) → medication → identity → AI consult → pharmacy (self-attest here) → confirm & pay. Geolocation removed, Utah attestation moved to the pharmacy screen, 3-state status system added, DPG async flow launched at $19.' },
          ] }] },
        { k: 'Key decisions', b: ['Five calls shaped the redesign.'],
          blocks: [{ type: 'decisions', items: [
            { h: 'Move self-attestation to the pharmacy screen', b: 'The GPS prompt was a trust-killer that failed frequently on mobile. Moving the Utah checkbox to pharmacy selection — where the question is contextually obvious — removed the upfront ask and added a clear exit to video visits for out-of-state users.' },
            { h: 'Shift the primary conversion event to phone capture', b: 'A completed refill is too rare to optimise paid campaigns against. Replacing “start your refill” with a phone field, reframed as “get access to your private portal,” creates a re-engagement pool from the 96% who don’t finish.' },
            { h: 'Explicit prescription-history opt-in', b: 'Research surfaced a WTF moment when prescription data appeared without warning. An explicit opt-in before the Surescripts pull turns a trust violation into a trust-building moment.' },
            { h: 'Refills → renewals positioning', b: 'People expect refills to be as easy as replying “yes” to a CVS text. Renewals are different — running out, needing a new authorization. The reframe positions Doctronic against a harder, more frustrating problem, which is the one it actually solves.' },
            { h: 'Deep-link session state as a prerequisite for re-engagement', b: 'Re-engagement messages are useless without a resumable URL. A user who clicks “resume your refill” and lands at step 1 abandons again immediately. Every drop-off point needed a URL that restores exact session state before lifecycle SMS could work.' },
          ] }] },
        { k: 'What shipped', b: ['Six releases in six weeks.'],
          blocks: [{ type: 'releases', rows: [
            ['v1.13.1', 'May 28', 'New refill landing page — trust signals, FAQ, ‘In the Press’ bar, A/B test support'],
            ['v1.14.0', 'Jun 2', 'Full flow overhaul — formulary state handling, error redesign, Utah-language removal'],
            ['v1.14.0', 'Jun 2', 'Analytics v1.3.0 — real-time tracking of upcoming, approved and denied refill requests'],
            ['v1.14.2', 'Jun 4', 'Mobile fix — refill chat message pinned above the keyboard'],
            ['v1.15.0', 'Jun 8', '3-state prescription status system — clearer patient visibility'],
            ['v1.15+', 'Jun 9', 'Automated DPG refill flow — lifecycle SMS plus async provider review at $19'],
          ] }] },
        { k: 'Outcomes', b: [],
          blocks: [{ type: 'outcomes', items: [
            { f: 'National press', h: 'Washington Post, Politico, Salt Lake Tribune', b: 'Coverage at launch as the first AI-authorized prescription refill in the United States.' },
            { f: 'Retention signal', h: '85% return rate after first refill', b: 'Utah patients who complete a first refill come back for a second — the strongest retention signal in the product.' },
            { f: 'Lifecycle infrastructure', h: '~300/day addressable pool', b: '75–300 pharmacy refill reminders addressable daily — a market built from design decisions rather than code.' },
            { f: 'Conversion KPI', h: '6% July target, from 0.04%', b: 'Eligibility → AI decision, up from a ~0.04% checkout rate in February. The IDV redesign is the primary lever.' },
          ] }] },
        { k: 'Reflection', b: ['Designing for AI products means designing the emotional preconditions for the AI to be useful.'],
          blocks: [{ type: 'callout', tone: 'good', h: 'What I’m proudest of', b: 'The positioning shift from “refills” to “renewals” — a single word that reframed the entire product promise and made every downstream design decision clearer.' }] },
      ],
      result: ['Shipped the **first AI-authorized prescription refill in the US**, covered by national press', '**85% return rate** after a first completed refill', 'Built the lifecycle infrastructure — deep-link session state, 3-state status, DPG async flow — that made re-engagement possible at all'],
      metrics: [{ v: '85%', l: 'return after first refill' }, { v: '6 in 6', l: 'releases in six weeks' }, { v: '72%', l: 'IDV drop-off diagnosed' }],
      shots: ['Before: GPS prompt on step 2', 'After: self-attestation at pharmacy selection'],
    },
    {
      id: 'goodrx', client: 'GoodRx', tint: 'var(--violet-2)', year: '2025',
      title: 'Telehealth subscription platform — 0-to-1, to an all-time-high 26.1% conversion',
      role: 'Sr. Product Designer', dates: 'Apr 2025 – Jan 2026', discipline: 'Telehealth',
      cats: ['health', 'numbers', 'zero-to-one'],
      headline: { v: '26.1%', l: 'funnel conversion, all-time high' },
      story: 'GoodRx had months to ship its first subscription product into a market Hims and Roman had already proven. Every screen touched medical compliance, so legal and clinical were in the room daily. The fast path was a single ED flow. I argued for the slower one — and then spent the six months after launch taking the funnel apart to find out why people were leaving.',
      pivot: { h: 'The pivot', b: 'Legal wanted a standalone emergency-screening question early in the flow. It was reading as alarming and pushing users out before intake. Instead of arguing to remove it, **I reframed the ask: merge the disclaimers into the Terms & Conditions screen with tappable detail links.** Same legal coverage, different placement. It took several rounds to land — and became the template for how I worked with legal on the rest of the funnel.' },
      sections: [
        { k: 'Problem', b: ['GoodRx wanted telehealth, prescription management, and discreet home delivery bundled into one subscription — live in months, against competitors who had already proven the model.', 'I owned design end-to-end: onboarding, treatment preference, intake, and post-purchase. Every screen existed partly to manage real liability around treatment claims and health screening, so nothing shipped without legal review.'] },
        { k: 'Discover', b: ['Post-launch I diagnosed a **36% drop-off** during onboarding — then found the problem started earlier than that: the landing page itself was losing **86.3% of visitors** before they ever began.', 'Reading the funnel step by step separated the friction that was protecting the company from the friction that was just badly placed. That distinction is what made the fixes survivable in legal review.'] },
        { k: 'Design', b: ['Architecturally, I pushed for a reusable **Conditions Platform** rather than a purpose-built ED flow: shared onboarding, intake, prescription review, and subscription management, with condition-specific content swapped in per treatment. More upfront complexity on a tight deadline — in exchange for future conditions launching by reconfiguring content instead of rebuilding screens.', 'We integrated Wheel (telehealth) and Truepill (fulfillment) into one conditions-aware dashboard to support it.'] },
        { k: 'Solution', b: ['We launched on time in **May 2025** — and the platform bet paid off exactly as planned when **GLP-1, hair loss and skincare** treatment lines launched on the same structure.'] },
        { k: 'Testing', b: ['Three shipped, measured interventions:'], list: ['Merged emergency screening into T&Cs → onboarding-start conversion **17% → 20%**', 'Removed 3 warm-up questions and 2 milestone pages → reach-to-signup **5.54% → 7.84%**', 'Personalized dosage paths for returning patients → treatment-to-subscription **20% → 24.6%**'], after: 'Paired with a landing page redesign (**+24% CTR**), overall funnel conversion reached an all-time-high **26.1%**, up from 15.6%.' },
      ],
      result: ['First subscription product shipped on time, **May 2025**', 'Conversion diagnosis → intervention → **26.1% all-time high** (from 15.6%)', 'Platform architecture became the template for **3+ subsequent treatment lines**'],
      metrics: [{ v: '26.1%', l: 'funnel conversion' }, { v: '+24%', l: 'landing page CTR' }, { v: '3+', l: 'lines on the platform' }],
      shots: ['Before: standalone emergency-screening screen', 'After: merged into T&Cs with expandable detail'],
    },
    {
      id: 'stripes', client: 'Stripes Beauty', tint: 'var(--plum)', year: '2022',
      title: 'Founding design for a 0-to-1 menopause wellness brand',
      role: 'Founding Designer (at Amyris)', dates: 'Sep 2021 – Aug 2023', discipline: 'Brand + eCommerce',
      cats: ['brand', 'ecom', 'zero-to-one', 'numbers'],
      headline: { v: '+25%', l: 'portfolio conversion YoY' },
      story: 'Stripes launched in 2022 as a menopause-focused wellness brand co-founded by Naomi Watts — a category with almost no confident e-commerce precedent at the time, on a launch date that would not move. Partway through, the design director and a senior designer left the company within weeks of each other.',
      pivot: { h: 'The pivot', b: 'With half of design leadership gone and the date fixed, **a colleague and I split the remaining high-fidelity work and took over stakeholder management ourselves** — weekly with the VP of Product, keeping the founders aligned and the timeline intact without a design director in the room.' },
      sections: [
        { k: 'Problem', b: ['A new brand in a category most retailers were still too squeamish to name, with no established visual or merchandising language to borrow — and a hard launch deadline set before the team was fully staffed.'] },
        { k: 'Discover', b: ['The category research kept returning the same thing: shoppers did not want to be marketed *to* about menopause. They wanted a brand that already understood it and would get to the point.'] },
        { k: 'Design', b: ['I drove the shopping funnel strategy — not just for Stripes, but across the broader Amyris portfolio: **Biossance, JVN Hair, Rose Inc, Pipette, Costa Brazil** — covering advanced search, cart and promo logic, livestream shopping, and global navigation.'] },
        { k: 'Solution', b: ['Stripes launched **on schedule in 2022**, with a storefront and funnel that treated the customer as informed rather than fragile.'] },
        { k: 'Testing', b: ['Funnel work across the portfolio was measured year over year: **+25% conversion** and **−13% cart abandonment**.'] },
      ],
      result: ['Launched **on schedule in 2022** despite the leadership gap', 'Portfolio funnel work drove **+25% conversion** and **−13% cart abandonment** YoY'],
      metrics: [{ v: '+25%', l: 'conversion YoY' }, { v: '−13%', l: 'cart abandonment' }, { v: '6', l: 'brands in scope' }],
      shots: ['Launch storefront — editorial system', 'Funnel work across the portfolio'],
    },
    {
      id: 'shopex', client: 'Estée Lauder', tint: 'var(--slate)', year: '2022',
      title: 'Enterprise search for 5,000 store associates across 7+ luxury brands',
      role: 'Lead Product Designer, ShopEx', dates: '2022', discipline: 'Enterprise',
      cats: ['enterprise', 'numbers'],
      headline: { v: '47s → 11s', l: 'average lookup time' },
      story: 'A customer asks for a shade in a MAC store. The associate has to check stock at a sister location, pull the customer’s last purchase, and confirm the formula — across six tools, while the customer stands there.',
      pivot: { h: 'The pivot', b: 'The team framed it as a search-results problem. Timing the real task showed it was a **context-switching** problem: 47 seconds per lookup, ×80 customers a day, ×5,000 associates — roughly **50 selling-hours lost per store per week.** That reframe funded a single shell instead of six better filters.' },
      sections: [
        { k: 'Problem', b: ['ShopEx is the in-store POS behind the Estée portfolio, and search is the front door to every task in it. Associates were tabbing between six tools mid-sale, and every lookup was a context switch with a customer waiting.'] },
        { k: 'Discover', b: ['I shadowed associates at four stores across three brands during real selling hours and mapped the twelve most common lookup paths — which is where the 47-second number came from.'] },
        { k: 'Design', b: ['One search shell with scoped filters — product, customer, inventory, loyalty — pinned recents, and a results layout that adapts per scope. Keyboard shortcuts were iterated with engineering until they felt native to the POS rather than bolted onto it.'] },
        { k: 'Solution', b: ['A single front door to every lookup, usable without taking your hands off the keyboard or your attention off the customer.'] },
        { k: 'Testing', b: ['Lookup time dropped **47s → 11s**, a **76% cut**, and the pattern rolled out as the search standard across **30 brands** and 5,000+ daily users.'] },
      ],
      result: ['Lookup **47s → 11s**, a **76%** reduction', 'Adopted as the search standard across **30 brands**'],
      metrics: [{ v: '47s → 11s', l: 'average lookup' }, { v: '30', l: 'brands rolled out' }, { v: '5,000+', l: 'daily users' }],
      shots: ['Scoped search shell inside the POS', 'Results layout per scope'],
    },
    {
      id: 'quicken', client: 'Quicken', tint: 'var(--violet)', year: '2021',
      title: 'A retirement calculator you can actually play with',
      role: 'Product + Motion Designer', dates: '2021', discipline: 'Fintech',
      cats: ['numbers', 'enterprise'],
      headline: { v: '81% → 34%', l: 'abandon rate' },
      story: 'Quicken Premier’s retirement calculator had 14 fields, one submit button, and a single “good luck” number at the end. Four out of five people never finished it.',
      pivot: { h: 'The pivot', b: 'In testing, every single user tried to ask a follow-up question — *what if I retire two years later, what if the market dips* — and the product had no way to answer. **The fix was not fewer fields. It was making the model interactive instead of submittable.**' },
      sections: [
        { k: 'Problem', b: ['Retirement planning is emotionally loaded, and the tool treated it like a tax form: inputs go in, anxiety comes out, and the assumptions are off limits. Abandon rate sat at **81%**.'] },
        { k: 'Discover', b: ['Sessions with 8 people across three income brackets, all of whom wanted to negotiate with the model rather than submit to it.'] },
        { k: 'Design', b: ['Every input became a scrubbable slider. I prototyped the feel first in After Effects and Principle, then worked with engineering so each drag re-runs the real model live, with the outcome figure animating between values like a slot machine slowing down.'] },
        { k: 'Solution', b: ['A calculator that answers “what if” in the same gesture as the question.'] },
        { k: 'Testing', b: ['Session time went up **4.2×**, abandon rate fell **81% → 34%**, and the slider was extracted into a Premier-wide primitive now used in **11 tools** across mortgage, tax, and budgeting.'] },
      ],
      result: ['Session time **4.2×**; abandon rate **81% → 34%**', 'Slider became a design-system primitive in **11 tools**'],
      metrics: [{ v: '4.2×', l: 'session time' }, { v: '81% → 34%', l: 'abandon rate' }, { v: '11', l: 'tools using it' }],
      shots: ['Scrubbable slider system', 'Outcome chart, live states'],
    },
    {
      id: 'sephora', client: 'Sephora', tint: 'var(--plum)', year: '2020',
      title: 'Five-minute training for 30,000 beauty advisors',
      role: 'Product Designer, Learning & Development', dates: '2020', discipline: 'Internal tools',
      cats: ['enterprise'],
      headline: { v: '94%', l: 'weekly active in pilot' },
      story: 'Sephora was rolling out 200+ new SKUs a year, and the training for them lived in PDFs, Slack threads, and a Drive nobody had access to. Advisors were expected to know the products cold, mid-shift, with a customer waiting.',
      pivot: { h: 'The pivot', b: 'Field research produced one constraint that decided the whole product: advisors have **5–7 minutes between customers**. Long enough to learn one thing, nowhere near long enough to open a deck. **The five-minute drop became the atomic unit** — everything else was designed around it.' },
      sections: [
        { k: 'Problem', b: ['Advisors could not find what they needed mid-shift, managers could not prove their team was current, and brand partners had no idea whether their training was landing.'] },
        { k: 'Discover', b: ['I shadowed advisors during peak retail hours to see when learning actually happens — which turned out to be in the gaps, not in scheduled sessions.'] },
        { k: 'Design', b: ['A mobile-first library of five-minute video drops, streaks to make repeat use feel worth it, search that respects shift context, and a manager dashboard that converts completion into compliance proof for brand partners.'] },
        { k: 'Solution', b: ['Training that fits the gap between two customers, and reporting that makes that provable up the chain.'] },
        { k: 'Testing', b: ['A four-store pilot ran before global rollout and landed at a **94% weekly-active rate**; it became the standard delivery channel for new product launches to **30,000 advisors**.'] },
      ],
      result: ['**94%** weekly-active rate across pilot stores', 'Standard launch-training channel for **30,000** advisors'],
      metrics: [{ v: '94%', l: 'weekly active' }, { v: '30k', l: 'advisors' }, { v: '5 min', l: 'average session' }],
      shots: ['Drop library on mobile', 'Manager compliance dashboard'],
    },
    {
      id: 'homebase', hackathon: true, badge: 'Hackathon', client: 'HomeBase', tint: 'var(--slate)', year: '2021',
      title: 'A community platform for mutual aid, built in a weekend',
      role: 'UX/Product Designer — discovery research, project management, end-to-end UI/UX',
      dates: '2021 · SacHacks III', discipline: 'Civic / social impact',
      link: { label: 'Read the Devpost writeup ↗', url: 'https://devpost.com/software/homebase-dcbwt5' },
      cats: ['zero-to-one'],
      headline: { v: 'Winner', l: 'Best Entertaining Hack' },
      story: 'Twelve months into the pandemic, unemployment in cities like Los Angeles sat at 10.6% against a 7.0% national average — and at the same time, neighbours were organising mask and PPE drives for frontline workers faster than any institution could. HomeBase was built for that second thing: a mobile platform where community members exchange donations, services and volunteer time directly.',
      pivot: { h: 'The reframe', b: 'The team started from a charity-directory idea. The research turned it into something closer to a neighbourhood exchange — the question became **“How might we make essential resources available for communities that are under-represented?”** which put discovery and local proximity, not org listings, at the centre of the product.' },
      sections: [
        { k: 'Problem', b: ['People wanted to help locally and could not find where to start. Giving was spiking, but discovery was fragmented across social posts, group texts and org-by-org websites — and the communities most in need were the least visible in all of it.'] },
        { k: 'Discover', b: ['Concepting and brainstorming in Miro, then a rapid survey during the research phase. The results were aggregated into user flows, a primary persona (Ezra), and a set of How-Might-We statements that scoped the build.', 'The finding that shaped everything: **people did not feel connected** to the causes around them, even while wanting to contribute.'] },
        { k: 'Design', b: ['Wireframes and high-fidelity screens in Figma: search and filtering across causes, volunteer registration for local events, direct donation of funds or resources, interactive maps to locate events and organisations nearby, and in-app individual and group messaging to keep supporters engaged after the first action.', 'The intended next layer was data-driven surfacing — using LAUS unemployment and COVID-spread datasets to push the most under-served programmes to the top of discovery rather than the best-marketed ones.'] },
        { k: 'Solution', b: ['One mobile app covering the full loop: find a cause nearby, show up or give, then stay in contact with the people you did it with.'] },
        { k: 'Testing', b: ['The prototype was tested with real users inside the hackathon window, which validated the core flow and surfaced functionality issues the team resolved before the final high-fidelity pass.', 'It won **Best Entertaining Hack** at SacHacks III. The honest constraint: the compressed timeline meant research was a survey and a handful of sessions, not the depth the problem deserves — which is exactly where the team wanted to take it next.'] },
      ],
      result: ['**Winner — Best Entertaining Hack**, SacHacks III', 'Validated end-to-end flow: discover → give or volunteer → stay connected', 'Three-person team after a mid-hackathon pivot; Dan led discovery, PM and end-to-end UI/UX'],
      metrics: [{ v: 'Winner', l: 'Best Entertaining Hack' }, { v: '1', l: 'weekend, concept to prototype' }, { v: '3', l: 'designers, after a pivot' }],
      shots: ['Discovery map and cause search', 'Volunteer registration flow'],
    },
  ];

  function Rich({ t, as = 'span', ...rest }) {
    const As = as;
    return <As {...rest}>{String(t).split(/(\*\*[^*]+\*\*)/g).map((s, i) =>
      s.startsWith('**') && s.endsWith('**')
        ? <strong key={i} style={{ fontWeight: 600, color: 'var(--ink)' }}>{s.slice(2, -2)}</strong>
        : <React.Fragment key={i}>{s}</React.Fragment>)}</As>;
  }

  Object.assign(window, { PROJECTS: P, Rich });
})();
